# Generated by Django 3.0.2 on 2021-07-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20210719_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='foto',
            field=models.CharField(max_length=1000),
        ),
    ]
